/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.5.3-260
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import {
    CallParams,
    callFunction,
    registerService,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v2';


// Services

export interface RaribleTestnetApiDef {
    download: (url: string, callParams: CallParams<'url'>) => string | Promise<string>;
    get_all_assets: (size: string, continue_token: string, callParams: CallParams<'size' | 'continue_token'>) => string | Promise<string>;
    get_owned_assets_by_collection: (collection_addr: string, size: string, callParams: CallParams<'collection_addr' | 'size'>) => string | Promise<string>;
    get_owned_collections: (owner_address: string, size: string, callParams: CallParams<'owner_address' | 'size'>) => string | Promise<string>;
}
export function registerRaribleTestnetApi(serviceId: string, service: RaribleTestnetApiDef): void;
export function registerRaribleTestnetApi(peer: FluencePeer, serviceId: string, service: RaribleTestnetApiDef): void;
       

export function registerRaribleTestnetApi(...args: any) {
    registerService(
        args,
        {
    "functions" : [
        {
            "functionName" : "download",
            "argDefs" : [
                {
                    "name" : "url",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "get_all_assets",
            "argDefs" : [
                {
                    "name" : "size",
                    "argType" : {
                        "tag" : "primitive"
                    }
                },
                {
                    "name" : "continue_token",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "get_owned_assets_by_collection",
            "argDefs" : [
                {
                    "name" : "collection_addr",
                    "argType" : {
                        "tag" : "primitive"
                    }
                },
                {
                    "name" : "size",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "get_owned_collections",
            "argDefs" : [
                {
                    "name" : "owner_address",
                    "argType" : {
                        "tag" : "primitive"
                    }
                },
                {
                    "name" : "size",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        }
    ]
}
    );
}
      
// Functions
 

export function download(
    url: string,
    config?: {ttl?: number}
): Promise<string>;

export function download(
    peer: FluencePeer,
    url: string,
    config?: {ttl?: number}
): Promise<string>;

export function download(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                         (call %init_peer_id% ("getDataSrv" "url") [] url)
                        )
                        (call -relay- ("op" "noop") [])
                       )
                       (xor
                        (seq
                         (call "12D3KooWD7CvsYcpF9HE9CCV9aY3SJ317tkXVykjtZnht2EbzDPm" ("749ccd29-4f4d-46be-8c4b-8bb9479dddbf" "download") [url] res)
                         (call -relay- ("op" "noop") [])
                        )
                        (seq
                         (call -relay- ("op" "noop") [])
                         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [res])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                    )
    `
    return callFunction(
        args,
        {
    "functionName" : "download",
    "returnType" : {
        "tag" : "primitive"
    },
    "argDefs" : [
        {
            "name" : "url",
            "argType" : {
                "tag" : "primitive"
            }
        }
    ],
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}

 

export function get_all_assets(
    size: string,
    continue_token: string,
    config?: {ttl?: number}
): Promise<string>;

export function get_all_assets(
    peer: FluencePeer,
    size: string,
    continue_token: string,
    config?: {ttl?: number}
): Promise<string>;

export function get_all_assets(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                          (call %init_peer_id% ("getDataSrv" "size") [] size)
                         )
                         (call %init_peer_id% ("getDataSrv" "continue_token") [] continue_token)
                        )
                        (call -relay- ("op" "noop") [])
                       )
                       (xor
                        (seq
                         (call "12D3KooWD7CvsYcpF9HE9CCV9aY3SJ317tkXVykjtZnht2EbzDPm" ("749ccd29-4f4d-46be-8c4b-8bb9479dddbf" "get_all_assets") [size continue_token] res)
                         (call -relay- ("op" "noop") [])
                        )
                        (seq
                         (call -relay- ("op" "noop") [])
                         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [res])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                    )
    `
    return callFunction(
        args,
        {
    "functionName" : "get_all_assets",
    "returnType" : {
        "tag" : "primitive"
    },
    "argDefs" : [
        {
            "name" : "size",
            "argType" : {
                "tag" : "primitive"
            }
        },
        {
            "name" : "continue_token",
            "argType" : {
                "tag" : "primitive"
            }
        }
    ],
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}

 

export function get_owned_collections(
    owner_address: string,
    size: string,
    config?: {ttl?: number}
): Promise<string>;

export function get_owned_collections(
    peer: FluencePeer,
    owner_address: string,
    size: string,
    config?: {ttl?: number}
): Promise<string>;

export function get_owned_collections(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                          (call %init_peer_id% ("getDataSrv" "owner_address") [] owner_address)
                         )
                         (call %init_peer_id% ("getDataSrv" "size") [] size)
                        )
                        (call -relay- ("op" "noop") [])
                       )
                       (xor
                        (seq
                         (call "12D3KooWD7CvsYcpF9HE9CCV9aY3SJ317tkXVykjtZnht2EbzDPm" ("749ccd29-4f4d-46be-8c4b-8bb9479dddbf" "get_owned_collections") [owner_address size] res)
                         (call -relay- ("op" "noop") [])
                        )
                        (seq
                         (call -relay- ("op" "noop") [])
                         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [res])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                    )
    `
    return callFunction(
        args,
        {
    "functionName" : "get_owned_collections",
    "returnType" : {
        "tag" : "primitive"
    },
    "argDefs" : [
        {
            "name" : "owner_address",
            "argType" : {
                "tag" : "primitive"
            }
        },
        {
            "name" : "size",
            "argType" : {
                "tag" : "primitive"
            }
        }
    ],
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}

 

export function get_owned_assets_by_collection(
    collection_addr: string,
    size: string,
    config?: {ttl?: number}
): Promise<string>;

export function get_owned_assets_by_collection(
    peer: FluencePeer,
    collection_addr: string,
    size: string,
    config?: {ttl?: number}
): Promise<string>;

export function get_owned_assets_by_collection(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                          (call %init_peer_id% ("getDataSrv" "collection_addr") [] collection_addr)
                         )
                         (call %init_peer_id% ("getDataSrv" "size") [] size)
                        )
                        (call -relay- ("op" "noop") [])
                       )
                       (xor
                        (seq
                         (call "12D3KooWD7CvsYcpF9HE9CCV9aY3SJ317tkXVykjtZnht2EbzDPm" ("749ccd29-4f4d-46be-8c4b-8bb9479dddbf" "get_owned_assets_by_collection") [collection_addr size] res)
                         (call -relay- ("op" "noop") [])
                        )
                        (seq
                         (call -relay- ("op" "noop") [])
                         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [res])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                    )
    `
    return callFunction(
        args,
        {
    "functionName" : "get_owned_assets_by_collection",
    "returnType" : {
        "tag" : "primitive"
    },
    "argDefs" : [
        {
            "name" : "collection_addr",
            "argType" : {
                "tag" : "primitive"
            }
        },
        {
            "name" : "size",
            "argType" : {
                "tag" : "primitive"
            }
        }
    ],
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}
